name: workflow for quiz app


on: 
  push:
    branches: [master]
  pull_request:
    branches: [master]
    
    
    
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2

      - name: Setup Nodejs environment
        uses: actions/setup-node@v1.4.2
      
      # Runs a set of commands using the runners shell
      - name: Github action for yarn
        uses: Borales/actions-yarn@v2.3.0
        with:
          cmd: install
          
      - name: Make build
        run: yarn build
        
      - name: Install surge
        run: npm install --global surge
        
      - name: Deploy on surge
        run: surge ./build quiz-app_knowmi.surge.sh --token ${{ secrets.SURGE_TOKEN }}
